name: Build beta

env:
  SLN_PATH: Source/

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build beta
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive # Updates the Languages submodule
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
      
    - name: Install Mod Dependencies
      run: dotnet restore ${{ env.SLN_PATH }}

    - name: Build Mod
      run: dotnet build ${{ env.SLN_PATH }} --configuration Release --no-restore

    - name: Package files
      run: |
        mkdir Multiplayer
        mv About/ Assemblies/ AssembliesCustom/ Defs/ Languages/ Textures/ Multiplayer
        zip -r Multiplayer-beta.zip Multiplayer/ 

    - name: Upload Mod Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Multiplayer-beta
        path: Multiplayer
    
    - name: Clean up last release
      continue-on-error: true
      run: |
        gh release delete --cleanup-tag --yes "continuous"
    
    - name: Upload new release
      run: |
        gh release create --target "${{ github.sha }}" --title "Continuous" --notes "This 'alpha' release is an automatically generated snapshot of the current state of development. It is continuously updated with work-in-progress changes that may be broken, incomplete, or incompatible." --draft "continuous"
        gh release upload "continuous" Multiplayer-beta.zip
        gh release edit "continuous" --draft=false
